### PR TITLE
Support custom source and local source

### PR DESCRIPTION
**Pull request by veightz**
Custom source:

```
git "git@github.com:xxxx/yyyy.git", "master", :files => ["*.swift"] 
```

Local source:

```
local "xxxx", "../xxxx",:files => ["*.swift"] 
```

### CODE REVIEW

**Comment by devxoul** [comment]
@veightz, Cool. Can you write a test for it?

**Comment by veightz** [comment]
@devxoul , I have added some codes for testing local source and custom source. I'm not good at Ruby development, so could you review them?

**Comment by numbbuaa** [comment]
@devxoul This is a practical feature. I expect you could review and add it in a new version.

**Comment by devxoul** [comment]
Hey guys, sorry for delay. I completely forgot it :( This is pretty cool feature. Thanks to @veightz for his work and thanks to @numbbuaa for reminding me. This feature has been shipped in [0.8.0 release](https://github.com/devxoul/CocoaSeeds/releases/tag/0.8.0) :smile::+1:

**Pull request merged**
