### PR TITLE
Update to support CocoaPods 1.0

### PR DESCRIPTION
**Pull request by argon**

### CODE REVIEW

**Comment by devxoul** [comment]
@argon, Thanks! can you please exclude the `version.rb` file from diff?

**Comment by argon** [comment]
Done

**Comment by argon** [comment]
@devxoul can we get this merged? I had forgotten that I'm still using my own fork.

**Comment by devxoul** [comment]
@argon, I had a question but forgot it. My apology :pray: How about making xcodeproj dependency version to `>= 0.28` to let CocoaPods < 1.0 users available to use CocoaSeeds?

**Comment by argon** [comment]
@devxoul done

**Comment by devxoul** [comment]
This is cool. I'll merge it just after the CI has done :smile:

**Comment by argon** [comment]
I have raised the minimum ruby version to keep activesupport happy.

**Comment by argon** [comment]
@devxoul There is another problem with the CI:

```
Seeds::Exception: JLToast: Couldn't find the repository.
```

Any ideas?

**Comment by devxoul** [comment]
@argon, Yeah, that's because I removed the JLToast repo from BitBucket :( I created again and retried the CI. Dont' worry!

**Comment by argon** [comment]
@devxoul there's another problem now. The tests pass locally on my machine.

**Comment by devxoul** [comment]
~~It seems that uppercases are not allowed in BitBucket repo URLs :( I'm gonna make a new PR to force BitBucket URLs lowercase.~~ => It works on git cloning

**Comment by devxoul** [comment]
I think it was just a cache problem :(

**Comment by argon** [comment]
Thanks!

**Comment by argon** [comment]
@devxoul One more thing: Would you be able to create a new release for this?

**Comment by devxoul** [comment]
@argon Of course!
- https://github.com/devxoul/CocoaSeeds/releases/tag/0.7.1
- https://rubygems.org/gems/cocoaseeds/versions/0.7.1

**Pull request merged**
