### PR TITLE
Supported the legacy target which uses an external build tool

### PR DESCRIPTION
**Pull request by ra1028**

### CODE REVIEW

**Comment by devxoul** [comment]
Thank you for your work, @ra1028!
Could you please make an explanation of what your PR exactly does?
What does 'legacy target' mean?

Thanks!

**Comment by ra1028** [comment]
Hi, @devxoul !
'legacy target' means target which uses an external build system such as Makefile.
'legacy target' is treated as class of 'Xcodeproj::Project::Object::PBXLegacyTarget' on gem [Xcodeproj](http://www.rubydoc.info/github/CocoaPods/Xcodeproj/Xcodeproj/Project/Object/PBXLegacyTarget).
So, CocoaSeeds was crashed at core.rb.

Crash Log

```
/path/to/project/cocoaseeds/core.rb:383:in `block in configure_phase': undefined method `sources_build_phase' for <PBXLegacyTarget name=`Strategy` UUID=`secret`>:Xcodeproj::Project::Object::PBXLegacyTarget (NoMethodError)
    from /path/to/project/cocoaseeds/cocoaseeds/core.rb:382:in `each'
    from /path/to/project/cocoaseeds/cocoaseeds/core.rb:382:in `configure_phase'
    from /path/to/project/cocoaseeds/cocoaseeds/core.rb:108:in `install'
    from /path/to/project/cocoaseeds/cocoaseeds/command.rb:8:in `run'
    from ./seed:5:in `<main>'
```

**Comment by devxoul** [comment]
Thanks!
This PR has been shipped in [0.3.0 release](https://github.com/devxoul/CocoaSeeds/releases/tag/0.3.0). :smile:

**Comment by ra1028** [comment]
@devxoul 
Thanks!

**Pull request merged**
